name: Test Suite Validation

on:
  pull_request:
    paths:
      - 'src/workflow/**/*.sh'
      - 'tests/**/*.sh'
      - 'tests/test_runner.sh'
      - '.github/workflows/validate-tests.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/workflow/**/*.sh'
      - 'tests/**/*.sh'

jobs:
  validate-tests:
    name: Validate Test Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up environment
        run: |
          echo "Setting up test environment..."
          sudo apt-get update -qq
          sudo apt-get install -y -qq shellcheck bats
      
      - name: Cache test dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/test-validation
            ~/.cache/test-fixtures
            src/workflow/.ai_cache
            tests/test-results
          key: test-cache-${{ hashFiles('tests/**/*.sh', 'src/workflow/**/*.sh') }}
          restore-keys: |
            test-cache-
            test-validation-
      
      - name: Track step timing
        run: echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      
      - name: Validate shell scripts syntax
        id: shellcheck
        run: |
          echo "::group::Running ShellCheck on test files"
          find tests -name "test_*.sh" -type f -print0 | \
            xargs -0 shellcheck --severity=warning --format=gcc || true
          echo "::endgroup::"
      
      - name: Make test scripts executable
        run: |
          echo "Making test scripts executable..."
          find tests -name "*.sh" -type f -exec chmod +x {} \;
          find src/workflow/lib -name "test_*.sh" -type f -exec chmod +x {} \;
      
      - name: Run unit tests
        id: unit-tests
        run: |
          echo "::group::Running Unit Tests"
          if [[ -f tests/test_runner.sh ]]; then
            chmod +x tests/test_runner.sh
            ./tests/test_runner.sh --unit --continue || echo "UNIT_TESTS_FAILED=true" >> $GITHUB_ENV
          else
            echo "::warning::test_runner.sh not found, running individual tests"
            for test in tests/unit/test_*.sh; do
              if [[ -f "$test" ]]; then
                echo "Running: $test"
                bash "$test" || echo "UNIT_TESTS_FAILED=true" >> $GITHUB_ENV
              fi
            done
          fi
          echo "::endgroup::"
        continue-on-error: true
      
      - name: Run library module tests
        id: lib-tests
        run: |
          echo "::group::Running Library Module Tests"
          failed=0
          total=0
          
          # Run all library module tests from tests/unit/lib/
          for test in tests/unit/lib/test_*.sh; do
            if [[ -f "$test" ]]; then
              test_name=$(basename "$test" .sh)
              echo "Testing: $test_name"
              ((total++))
              if bash "$test"; then
                echo "✅ $test_name passed"
              else
                echo "❌ $test_name failed"
                ((failed++))
              fi
            fi
          done
          
          echo "::endgroup::"
          echo "Library tests: $((total - failed))/$total passed"
          
          if [[ $failed -gt 0 ]]; then
            echo "LIB_TESTS_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        continue-on-error: true
      
      - name: Run integration tests
        id: integration-tests
        if: always()
        run: |
          echo "::group::Running Integration Tests"
          if [[ -f tests/test_runner.sh ]]; then
            ./tests/test_runner.sh --integration --continue || echo "INTEGRATION_TESTS_FAILED=true" >> $GITHUB_ENV
          else
            echo "::notice::No integration test runner found, skipping integration tests"
          fi
          echo "::endgroup::"
        continue-on-error: true
      
      - name: Generate test report
        if: always()
        run: |
          echo "::group::Test Suite Summary"
          echo "# Test Validation Report" > test-report.md
          echo "" >> test-report.md
          echo "**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> test-report.md
          echo "**Commit:** ${{ github.sha }}" >> test-report.md
          echo "" >> test-report.md
          
          # Unit tests status
          if [[ "${UNIT_TESTS_FAILED}" == "true" ]]; then
            echo "- ❌ Unit Tests: **FAILED**" >> test-report.md
          else
            echo "- ✅ Unit Tests: **PASSED**" >> test-report.md
          fi
          
          # Library tests status
          if [[ "${LIB_TESTS_FAILED}" == "true" ]]; then
            echo "- ❌ Library Module Tests: **FAILED**" >> test-report.md
          else
            echo "- ✅ Library Module Tests: **PASSED**" >> test-report.md
          fi
          
          # Integration tests status
          if [[ "${INTEGRATION_TESTS_FAILED}" == "true" ]]; then
            echo "- ❌ Integration Tests: **FAILED**" >> test-report.md
          else
            echo "- ✅ Integration Tests: **PASSED**" >> test-report.md
          fi
          
          echo "" >> test-report.md
          
          # Overall status
          if [[ "${UNIT_TESTS_FAILED}" == "true" ]] || \
             [[ "${LIB_TESTS_FAILED}" == "true" ]] || \
             [[ "${INTEGRATION_TESTS_FAILED}" == "true" ]]; then
            echo "## Overall Status: ❌ FAILED" >> test-report.md
            echo "TEST_SUITE_FAILED=true" >> $GITHUB_ENV
          else
            echo "## Overall Status: ✅ PASSED" >> test-report.md
          fi
          
          cat test-report.md
          echo "::endgroup::"
      
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.md
          retention-days: 30
      
      - name: Report test failures
        if: failure() || env.TEST_SUITE_FAILED == 'true'
        run: |
          echo "::error::Test suite validation failed!"
          echo "::error::Please run './tests/test_runner.sh' locally to see detailed errors"
          echo "::error::Check the test report artifact for details"
          
          if [[ "${UNIT_TESTS_FAILED}" == "true" ]]; then
            echo "::error::Unit tests failed - run './tests/test_runner.sh --unit --verbose'"
          fi
          
          if [[ "${LIB_TESTS_FAILED}" == "true" ]]; then
            echo "::error::Library module tests failed - check tests/unit/lib/test_*.sh"
          fi
          
          if [[ "${INTEGRATION_TESTS_FAILED}" == "true" ]]; then
            echo "::error::Integration tests failed - run './tests/test_runner.sh --integration --verbose'"
          fi
          
          exit 1
      
      - name: Report timing
        if: always()
        run: |
          DURATION=$(($(date +%s) - STEP_START))
          echo "::notice::Test suite validation duration: ${DURATION}s"
      
      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('test-report.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
