#!/usr/bin/env python3
"""
build_ai_helpers.py — Merge ai_helpers sub-files into a single YAML artifact.

Usage:
    python3 scripts/build_ai_helpers.py [--validate]

The sub-files in config/ai_helpers/ are the authoritative source.
The merged output (config/ai_helpers.yaml) is the backward-compatible artifact
consumed by ai_workflow.js and olinda_prompter via hardcoded paths.

Sub-files are merged in the order defined in MERGE_ORDER. _anchors.yaml must
always be first because YAML aliases (*behavioral_*) are resolved at parse time
and must follow their anchor definitions in the document.
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml as _yaml  # type: ignore
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False

REPO_ROOT = Path(__file__).parent.parent
SUB_FILES_DIR = REPO_ROOT / "config" / "ai_helpers"
OUTPUT_FILE = REPO_ROOT / "config" / "ai_helpers.yaml"
INDEX_FILE = SUB_FILES_DIR / "index.yaml"

MERGE_ORDER = [
    "_anchors.yaml",
    "documentation_prompts.yaml",
    "frontend_ux_prompts.yaml",
    "engineering_prompts.yaml",
    "workflow_steps.yaml",
    "language_tables.yaml",
    "specialist_prompts.yaml",
    "library_prompts.yaml",
    "review_prompts.yaml",
]

INDEX_HEADER = """\
# config/ai_helpers/index.yaml — Persona index (auto-generated)
#
# Machine-readable map: persona_key -> sub-file (relative to config/ai_helpers/)
# Generated by: python3 scripts/build_ai_helpers.py
#
# Use this file to locate any persona without grepping the monolith.
# Do not edit directly — regenerate with: python3 scripts/build_ai_helpers.py

"""

HEADER = """\
# AI Prompt Templates Configuration
# Purpose: Centralized AI prompt strings for workflow automation
# Version: 7.0.1
#
# Version history -> see CHANGELOG.md
#
# =============================================================================
# SECTION INDEX
# =============================================================================
# 1. REUSABLE BEHAVIORAL GUIDELINES (YAML Anchors)
#    _behavioral_actionable  -- output must be concrete and actionable
#    _behavioral_structured  -- structured analysis with explicit reasoning
#    _behavioral_generative  -- pure-generation tasks (commits, test files, bumps)
#
# 2. DOCUMENTATION PERSONAS
#    doc_analysis_prompt          -- incremental documentation updates
#    consistency_prompt           -- documentation quality assurance
#    technical_writer_prompt      -- comprehensive from-scratch documentation
#
# 3. FRONT-END & UX PERSONAS
#    front_end_developer_prompt   -- code implementation, performance, testing
#    e2e_test_engineer_prompt     -- browser automation and visual testing
#    ui_ux_designer_prompt        -- user research, visual design, interaction
#    tui_ux_designer_prompt       -- terminal UI/UX design
#
# 4. ENGINEERING PERSONAS
#    requirements_engineer_prompt -- requirements elicitation and specification
#    test_strategy_prompt         -- strategic test coverage (WHAT to test)
#    single_file_test_prompt      -- generate tests for a single file
#    quality_prompt               -- quick/targeted file-level code quality
#    issue_extraction_prompt      -- extract actionable issues from AI output
#
# 5. WORKFLOW STEP PROMPTS  (step2 ... step14)
#    step2_consistency_prompt     step3_script_refs_prompt
#    step5_directory_prompt       step6_test_review_prompt
#    step8_test_exec_prompt       step9_dependencies_prompt
#    step10_code_quality_prompt   step12_git_commit_prompt
#    step14_prompt_engineer_prompt
#
# 6. DIAGNOSTIC & PERFORMANCE PERSONAS
#    error_resilience_prompt      -- error handling patterns
#    markdown_lint_prompt         -- markdown quality review
#    configuration_specialist_prompt -- config file validation
#    observer_pattern_debugger_prompt / async_flow_debugger_prompt
#    data_structure_debugger_prompt / async_perf_engineer_prompt
#
# 7. LANGUAGE LOOKUP TABLES
#    language_specific_documentation / language_specific_quality
#    language_specific_testing
#
# 8. SPECIALIST PERSONAS
#    version_manager_prompt       aws_cloud_architect_prompt
#    javascript_developer_prompt  typescript_developer_prompt
#    python_developer_prompt      technical_project_manager_prompt
#    software_architect_prompt
#    (+ 30+ additional specialist and stub personas)
#
# 9. LIBRARY / FRAMEWORK PERSONAS  (library_architect ... spec_architect)
#
# 10. REVIEW & WORKFLOW AUTOMATION PERSONAS
#     security_analyst_prompt  api_contract_reviewer_prompt
#     cli_tui_engineer_prompt  llm_integration_engineer_prompt
#     devx_engineer_prompt     core_pipeline_engineer_prompt
#     accessibility_review_prompt  performance_review_prompt
# =============================================================================
#
# YAML Anchors for Token Efficiency:
# - Common behavioral guidelines defined once using anchors (&name)
# - Referenced by ALL personas to reduce duplication
# - Token savings vs. v3.0.0 baseline: ~1,560-1,755 tokens per workflow
#
# WARNING: GENERATED FILE -- do not edit directly.
#          Edit the sub-files in config/ai_helpers/ and run:
#            python3 scripts/build_ai_helpers.py
# =============================================================================

"""


def _strip_subfile_header(lines: list[str]) -> list[str]:
    """Remove the 3-line management comment at the top of each sub-file."""
    if (
        len(lines) >= 3
        and lines[0].startswith("# ")
        and lines[1].startswith("# Source sub-file")
        and lines[2].startswith("#\n")
    ):
        return lines[3:]
    return lines


def _write_index() -> None:
    """Generate index.yaml mapping every persona key to its source sub-file."""
    lines = [INDEX_HEADER]
    for filename in MERGE_ORDER:
        path = SUB_FILES_DIR / filename
        content = path.read_text()
        # Extract top-level keys by regex — sub-files can't be parsed standalone
        # because they contain YAML anchor aliases defined only in _anchors.yaml
        keys = re.findall(r'^([a-zA-Z_][a-zA-Z0-9_]*):', content, re.MULTILINE)
        if keys:
            lines.append(f"# {filename}\n")
            for key in keys:
                lines.append(f"{key}: {filename}\n")
            lines.append("\n")

    INDEX_FILE.write_text("".join(lines))
    total = sum(1 for ln in lines if ln and not ln.startswith("#") and ": " in ln)
    print(f"  Wrote {INDEX_FILE} ({total} entries)")


def _validate_yaml() -> int:
    if _HAS_YAML:
        try:
            with open(OUTPUT_FILE) as f:
                _yaml.safe_load(f)
            print("  YAML syntax valid")
            return 0
        except _yaml.YAMLError as e:
            print(f"ERROR: YAML validation failed:\n{e}", file=sys.stderr)
            return 1

    import subprocess
    result = subprocess.run(
        ["python3", "-c", f"import yaml; yaml.safe_load(open('{OUTPUT_FILE}').read())"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: YAML validation failed:\n{result.stderr}", file=sys.stderr)
        return 1
    print("  YAML syntax valid")
    return 0


def merge(validate: bool = False) -> int:
    missing = [f for f in MERGE_ORDER if not (SUB_FILES_DIR / f).exists()]
    if missing:
        print(f"ERROR: Missing sub-files: {missing}", file=sys.stderr)
        return 1

    parts = [HEADER]
    for filename in MERGE_ORDER:
        path = SUB_FILES_DIR / filename
        content = path.read_text()
        lines = content.splitlines(keepends=True)
        stripped = _strip_subfile_header(lines)
        parts.append("".join(stripped))

    merged = "".join(parts)
    OUTPUT_FILE.write_text(merged)
    print(f"Wrote {OUTPUT_FILE} ({len(merged.splitlines())} lines)")

    _write_index()

    if validate:
        return _validate_yaml()
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validate", action="store_true", help="Validate merged YAML after writing")
    args = parser.parse_args()
    sys.exit(merge(validate=args.validate))


if __name__ == "__main__":
    main()
